#!/bin/bash
#
# fplayer - watch last buffored flash movie (default in mplayer).
#   inspired by Ivan Agarkov script (http://habrahabr.ru/blogs/linux/104420/#comment_3258122)
#
# https://github.com/macie/linux-shell-scripts
#
# Copyright (c) 2011-2013 Maciej Żok <maciek.zok@gmail.com>
# MIT License (http://opensource.org/licenses/MIT)


show_help () { 
	echo "fplayer - watch last buffored flash movie (default in mplayer)."
	echo "Usage:"
	echo "  fplayer [options]"
	echo 
	echo "Options:"
	echo "  -p, --player <command>          use specified player"
	echo "  -o, --player-options <options>  set player options"
	echo "  -h, --help                      show this help"
	echo "  -v, --version                   show version number."
}


VERSION="1.0"
PLAYER=mplayer
PLAYER_OPTIONS=``
PID=`ps x | awk 'match($0,/libflashplayer.so/){print $1}' | head -n 1`
FD_ID=`lsof -p $PID | awk 'match($0,/Flash/){print $4}' | sed 's/[a-z]$//' | tail -1`


while [[ $1 == -* ]]; do
	case "$1" in
		-h|--help|-\?) show_help; exit 0;;
		-v|--version|-\?)
			echo "fplayer "$VERSION;
			echo
			echo "Copyright (c) 2013 Maciej Żok"
			echo "MIT License (http://opensource.org/licenses/MIT)"
			exit 0;;
		-p|--player) if (($# > 1)); then
            PLAYER=$2; shift 2
          else 
            echo "Error: no player specified." 1>&2
            exit 1
          fi ;;
		-o|--player-options) if (($# > 1)); then
            PLAYER_OPTIONS=$2; shift 2
          else 
            echo "Error: no player options specified." 1>&2
            exit 1
          fi ;;
		-*) echo "invalid option: $1" 1>&2; show_help; exit 1;;
	esac
done


exec $PLAYER $PLAYER_OPTIONS /proc/${PID}/fd/${FD_ID}

