#!/bin/bash
#
# lplayer - gapless loop player (using mplayer)
#   inspired by http://forum.gmusicbrowser.org/index.php?topic=100.0
#
# https://github.com/macie/linux-shell-scripts
#
# Copyright (c) 2011-2013 Maciej Żok <maciek.zok@gmail.com>
# MIT License (http://opensource.org/licenses/MIT)


show_help () { 
	echo "lplayer - gapless loop player (using mplayer)."
	echo "Usage:"
	echo "  lplayer [options] filename"
	echo 
	echo "Options:"
	echo "  -p, --playlist <filename>        use specified player"
	echo "  -o, --player-options <options>   set player options"
	echo "  -h, --help                       show this help"
	echo "  -v, --version                    show version number."
}


VERSION="1.0"
QUEUE_FILE=/tmp/lplayerqueue
CHANNELS="2"
SAMPLERATE="48000"
PLAYER=mplayer
PLAYER_OPTIONS="-nocache -nolirc -vc null -vo null -loop 0 \
-af resample=${SAMPLERATE} -ao pcm:nowaveheader:file=${QUEUE_FILE}"


if [[ $# -eq 0 ]]; then
	echo "Error: no audio file."
	exit 1
else
	echo "Press <q> to exit, <space> to pause/play"
fi;


while [[ $1 == -* ]]; do
	case "$1" in
		-h|--help|-\?)
			show_help; exit 0;;
		-v|--version|-\?)
			echo "lplayer "$VERSION;
			echo
			echo "Copyright (c) 2013 Maciej Żok"
			echo "MIT License (http://opensource.org/licenses/MIT)"
			exit 0;;
		-p|--playlist)
			PLAYER_OPTIONS="${PLAYER_OPTIONS} -playlist";;
		-o|--player-options) 
			if [[ $# -gt 1 ]]; then
				OPTIONS=${PLAYER_OPTIONS} $2; shift 2
			else 
				echo "Error: no player options specified." 1>&2
				exit 1
			fi ;;
		-*) echo "Invalid option: $1" 1>&2; show_help; exit 1;;
	esac
done


[[ -e $QUEUE_FILE ]] && rm $QUEUE_FILE
mkfifo $QUEUE_FILE

aplay -t raw -c $CHANNELS -f S16_LE -r $SAMPLERATE $QUEUE_FILE \
 &> $QUEUE_FILE.log &
$PLAYER $PLAYER_OPTIONS "$@" >/dev/null 2>&1
